### ISSUE TITLE
Антагонистическая беск игра

### ISSUE THREAD

**Issue by alldayalone** [NandreyN/OpRes_Outline#5]
**Describe the bug**
в Теореме 4 формула должна быть x, y0 <= x0, y0 <= x0 y

**Screenshots**

**Additional context**

**Comment by NandreyN** [comment]
![image](https://user-images.githubusercontent.com/14164714/59148083-8f4dec00-8a0c-11e9-9fea-e2a74596759a.png)
В лекциях не так, у меняв конспекте тоже. Скрин из лекции. Где ты видел свой вариант?

**Comment by vladrrv** [comment]
По логике должно быть как Паша сказал, потому что по переменной x берётся максимум, там кстати в доказательстве достаточности уже правильно написано

**Comment by NandreyN** [comment]
Хм, пересмотрю

**Comment by NandreyN** [comment]
Насколько я понял, в достаточности так: если справедливо для любым, то возьмем конкретные x_0, y_0. А максимумы и минимумы - из определения

**Comment by NandreyN** [comment]
В общем, как хотите, в доке я оставлю как в формулировке на лекции. Просто имейте в виду дял себя
